name: School Management API Deployment (Dev)

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "ap-south-1"
  ECR_REGISTRY: "120569634557.dkr.ecr.ap-south-1.amazonaws.com/school-management"
  
  SSH_PRIVATE_KEY_DEV: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
  EC2_HOST_DEV: ${{ secrets.EC2_HOST_DEV }} 
  EC2_USERNAME_DEV: ${{ secrets.EC2_USERNAME_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3600 seconds'
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload dev script
        uses: actions/upload-artifact@v3
        with:
          name: dev-script
          path: ./dev/script

      - name: Build Docker image
        run: |
          docker build -t school-management ./api
          docker save school-management -o school-management.tar

      - name: Publish school-management image artifact
        uses: actions/upload-artifact@v3
        with:
          name: school-management-image-artifact
          path: school-management.tar

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: school-management-image-artifact

      - name: Load Docker images
        run: |
          docker load -i school-management.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KE
