name: School Management API Deployment (Dev)

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "ap-south-1"
  SSH_PRIVATE_KEY_DEV: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
  EC2_HOST_DEV: ${{ secrets.EC2_HOST_DEV }} 
  EC2_USERNAME_DEV: ${{ secrets.EC2_USERNAME_DEV }}
  ECR_REGISTRY: "120569634557.dkr.ecr.ap-south-1.amazonaws.com/school-management"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: |
          docker build -t school-management ./api

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Tag and push image to Amazon ECR
        run: |
          docker tag school-management:latest ${{ env.ECR_REGISTRY }}:latest
          docker push ${{ env.ECR_REGISTRY }}:latest

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dev scripts
        uses: actions/download-artifact@v3
        with:
          name: dev-scripts
          path: dev-scripts

      - name: Copy scripts to dev-server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "${{ env.EC2_HOST_DEV }}"
          username: "${{ env.EC2_USERNAME_DEV }}"
          key: "${{ secrets.SSH_PRIVATE_KEY_DEV }}"
          port: 22
          source: dev-scripts/*
          target: "/home/ubuntu/"
        
      - name: Connect to dev-server
        uses: appleboy/ssh-action@master
        with:
          host: "${{ env.EC2_HOST_DEV }}"
          username: "${{ env.EC2_USERNAME_DEV }}"
          key: "${{ secrets.SSH_PRIVATE_KEY_DEV }}"
          port: 22
          script: |
            chmod +x /home/ubuntu/dev-scripts/build.sh
            chmod +x /home/ubuntu/dev-scripts/install.sh
            /home/ubuntu/dev-scripts/install.sh 
            /home/ubuntu/dev-scripts/build.sh "${{ env.ECR_REGISTRY }}" school-management "${{ env.AWS_REGION }}"
