name: School Management API Deployment (Dev)

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "ap-south-1"
  ECR_REGISTRY: "120569634557.dkr.ecr.ap-south-1.amazonaws.com/school-management"
  
  SSH_PRIVATE_KEY_DEV: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
  EC2_HOST_DEV: ${{ secrets.EC2_HOST_DEV }} 
  EC2_USERNAME_DEV: ${{ secrets.EC2_USERNAME_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3600 seconds'
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload dev script
        uses: actions/upload-artifact@v3
        with:
          name: dev-script
          path: ./dev/script

      - name: Build Docker image
        run: |
          docker build -t school-management ./api
          docker save school-management -o school-management.tar

      - name: Publish school-management image artifact
        uses: actions/upload-artifact@v3
        with:
          name: school-management-image-artifact
          path: school-management.tar

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Tag and push image to Amazon ECR
        run: |
          docker tag school-management:latest ${{ env.ECR_REGISTRY }}:latest
          docker push ${{ env.ECR_REGISTRY }}:latest

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dev script
        uses: actions/download-artifact@v3
        with:
          name: dev-script
          path: dev-script

      - name: Copy scripts to dev-server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          port: 22
          source: dev-script/*
          target: "/home/ubuntu/"
        
      - name: Connect to dev-server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          port: 22
          script: |
            chmod +x /home/ubuntu/dev-script/build.sh
            chmod +x /home/ubuntu/dev-script/install.sh
            /home/ubuntu/dev-script/install.sh 
            /home/ubuntu/dev-script/build.sh "${{ env.ECR_REGISTRY }}" school-management "${{ env.AWS_REGION }}"
