name: School Management API Deployment (Dev)

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "ap-south-1"
  ECR_REGISTRY: "120569634557.dkr.ecr.ap-south-1.amazonaws.com/school-management"
  
  SSH_PRIVATE_KEY_DEV: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
  EC2_HOST_DEV: ${{ secrets.EC2_HOST_DEV }} 
  EC2_USERNAME_DEV: ${{ secrets.EC2_USERNAME_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3600 seconds'
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload dev script
        uses: action
