name: School Management API Deployment (Dev)

on:
  push:
  workflow_dispatch:

env:
  AWS_REGION: "ap-south-1"
  EC2_HOST_DEV: "3.110.221.62"
  EC2_USERNAME_DEV: "ubuntu"
  ECR_REGISTRY: "354918382863.dkr.ecr.ap-south-1.amazonaws.com/school-management"
  AWS_ACCESS_KEY_ID: "AKIAVFIWIXUHQEEKG4TO"  # Replace with your access key
  AWS_SECRET_ACCESS_KEY: "g7dPOkSW2M1Bbqt3S7LzTrgs47PCbLcMsWwBG"  # Replace with your secret key

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3600 seconds'

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Upload dev scripts
        uses: actions/upload-artifact@v3
        with:
          name: dev-scripts
          path: ./env/dev/scripts

      - name: Build Docker image
        run: |
          docker build -t school-management ./api
          docker save school-management -o school-management.tar

      - name: Publish school-management image artifact
        uses: actions/upload-artifact@v3
        with:
          name: school-management-image-artifact
          path: school-management.tar

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download images artifact
        uses: actions/download-artifact@v3
        with:
          name: school-management-image-artifact

      - name: Load Docker images
        run: |
          docker load -i school-management.tar

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id "${{ env.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ env.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "${{ env.AWS_REGION }}"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker tag school-management $ECR_REGISTRY:latest
          docker push $ECR_REGISTRY:latest

      - name: Download dev scripts
        uses: actions/download-artifact@v3
        with:
          name: dev-scripts
          path: dev-scripts

      - name: Copy scripts to dev-server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "${{ env.EC2_HOST_DEV }}"
          username: "${{ env.EC2_USERNAME_DEV }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"  # You can also hardcode this for testing
          port: 22
          source: dev-scripts
          target: "/home/ubuntu/"
        
      - name: Connect to dev-server
        uses: appleboy/ssh-action@master
        with:
          host: "${{ env.EC2_HOST_DEV }}"
          username: "${{ env.EC2_USERNAME_DEV }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"  # You can also hardcode this for testing
          port: 22
          script: |
            chmod +x dev-scripts/build.sh
            chmod +x dev-scripts/install.sh
            dev-scripts/install.sh 
            dev-scripts/build.sh $ECR_REGISTRY school-management $AWS_REGION

      - name: Clean up artifacts
        uses: geekyeggo/delete-artifact@v5.1.0
        with:
          name: school-management-image-artifact
