name: School Management API Deployment (Dev)

on:
  push:
  workflow_dispatch:

env:
  AWS_REGION: "ap-south-1"
  EC2_HOST_DEV: "3.110.221.62"
  EC2_USERNAME_DEV: "ubuntu"
  ECR_REGISTRY: "354918382863.dkr.ecr.ap-south-1.amazonaws.com/school-management"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3600 seconds'

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Upload dev scripts
        uses: actions/upload-artifact@v3
        with:
       
